### ISSUE TITLE
lovelist页面竖图显示不全

### ISSUE THREAD

**Issue by BINBIN02** [furacas/hexo-theme-brave#2]
如题，插入竖图只显示图片上半部分，未能完全显示。
显示如图：
![image](https://github.com/furacas/hexo-theme-brave/assets/40969207/0146e0dd-1397-4bac-9cc7-e3db36befee6)
完整图片：
![8ebc2aca2fdfe0e2dd138d4dfd3dc7e](https://github.com/furacas/hexo-theme-brave/assets/40969207/77cb3505-3402-4c82-9207-ee197fa67759)

**Comment by furacas** [comment]
已经修复掉了 https://github.com/furacas/hexo-theme-brave/releases/tag/v1.5.0 
使用最新版本即可解决
